### ISSUE TITLE
Feature Request - Same Window Shadow defaults as system defaults

### ISSUE THREAD

**Issue by seanleavy** [yilozt/rounded-window-corners#11]
First all well done. Absolutely class work.

Just wanted to request the below. Feel free to close this if you dont wish to.

- Ability to restore default settings via GUI.
- Match the extension 'Window Shadow' defaults to the system defaults (ie. focused & unfocused window shadows are the same whether this extension is enabled or not) OR just have a toggle to ignore the 'Window Shadow' settings.

Thanks again for the contribution :+1: .

**Comment by yilozt** [comment]
The default style of window can be found in Gtk project:

[https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/theme/Default/_common.scss#L4053](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/theme/Default/_common.scss#L4053)

We can use it as default box-shadow of windows. We have to add a custom shadow behind windows, because original shadow has been cut out, so `ignore the 'Window Shadow'` is impossible.

Restore default settings is a good idea, I will add it to prefs.

**Comment by julianfairfax** [comment]
Yeah I agree defaults should be an option. Because otherwise it looks weird.

**Comment by yilozt** [comment]
Should be implemented in #30, There is the shadow looks like when enable / disable this extensions:

https://user-images.githubusercontent.com/32430186/183357834-074c7575-d3f3-42e3-a4b2-1916724c28a5.mp4
