### ISSUE TITLE
Avoid shadows bleeding to other monitors

### ISSUE THREAD

**Issue by MichalLebeda** [yilozt/rounded-window-corners#28]
Hi,
I have a multi monitor setup and shadows bleed to other monitors (where I usually have documentation, web etc.). Would it be possible to add feature that disables shadows for maximized windows? Already saw #24 which, to my knowledge, allows us to turn rounded corners on/off for maximized windows.

![image](https://user-images.githubusercontent.com/5246963/183291364-ab32948b-4bd9-49ec-891f-1ebe440bb1f4.png)

**Comment by yilozt** [comment]
Duplicate with #6, it should be fixed in the latest commit. 

Could you can test it because I don't have multi-monitor setup yet. The extension pack can be downloaded from [https://github.com/yilozt/rounded-window-corners/actions/runs/2807288003](https://github.com/yilozt/rounded-window-corners/actions/runs/2807288003), after download it, you can use `gnome-extensions install rounded-window-corners@yilozt.shell-extension.zip` to install it.

**Comment by yilozt** [comment]
Comfirm this issue has been fix, the shadow is hiden when window is maxmized.

![_Screenshot_](https://user-images.githubusercontent.com/32430186/183338568-94af01e1-abe3-4fa4-9434-bbcae7cf24c9.png)

**Comment by MichalLebeda** [comment]
Sorry for late response, the issue seems to be fixed
