### ISSUE TITLE
Some apps still have sharp corners

### ISSUE THREAD

**Issue by rashidi77** [yilozt/rounded-window-corners#4]
Gnome Tweaks and Videos (totem) still have bottom sharp corners. They are not Libadwaita or Libhandy apps. 

Platform:
Fedora 37 (rawhide)
Gnome 43.alpha / mutter-43.alpha

Screenshot:
![Screenshot from 2022-07-31 09-58-37](https://user-images.githubusercontent.com/93915281/182009660-919b0b31-42f8-4931-8e0c-063abab1af87.png)

**Comment by yilozt** [comment]
I think `gnome-tweaks` is a libhandy applications, because it has import libhandy, and it have rounded corners with some GTK theme like [`Colloid-gtk-theme`](https://github.com/vinceliuice/Colloid-gtk-theme)

```javascript
> cat /usr/bin/gnome-tweaks 
#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0+
# License-Filename: LICENSES/GPL-3.0

import gettext
import logging
import locale
import os.path
import optparse
import signal
import sys

import gi
gi.require_version("Gtk", "3.0")
gi.require_version("Handy", "1")
```

`totem` is similar with `gnome-tweaks`, I think this problem is relative with the Gtk-Theme. You can turn off `Skip Libhandy applications` in preferences to force keep rounded corners for those applications.

**Comment by yilozt** [comment]
`Skip Libhandy applications` is disabled default via commit [`13d97eab`](https://github.com/yilozt/rounded-window-corners/commit/13d97eabd4286f1b8ca2d9d901f738d8cd6365fd), this issue can be closed.
