### ISSUE TITLE
The shadow and border will not move or bend with extension Compiz Windows Effect

### ISSUE THREAD

**Issue by huge-pancake** [yilozt/rounded-window-corners#71]
Compiz Windows Effect: https://github.com/hermes83/compiz-windows-effect

The border and the shadow of the corner-rounded window will not work with this extension.

Fedora 38 (Fedora Rawhide), GNOME 43.0, Wayland

**Comment by yilozt** [comment]
This issue looks like #37, this extensions draw new shadow under windows because the original shadow of window have been cut out by rounded corners shader. The new shadow is not a part of window, it is drew under window, so Compiz Windows Effect can't apply to shadow.

Sorry that I have not find a way to apply effect from Compiz Windows Effect to shadow yet.

**Comment by huge-pancake** [comment]
OK, I see, thank you!
